### ISSUE TITLE
Non-Mod files are installed as user-provided mods

### ISSUE THREAD

**Issue by douira** [gorilla-devs/libium#13]
If there is a `.DS_Store` (or some other non-jar) file in the `.../mods/user` folder, then it is also copied into the mods folder during upgrading even though it should be ignored. Generally `.DS_Store`, and maybe also other dot files, should probably be ignored.

**Comment by Eskaan** [comment]
I think your error relates to ferium, not libium.

**Comment by theRookieCoder** [comment]
Moved to gorilla-devs/ferium#230
